// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-ahDaX5Xp8IeF0YcPS8YF2-DRpknFnQ',
    appId: '1:740971362749:web:03f840d7961c58eec43ad4',
    messagingSenderId: '740971362749',
    projectId: 'sparringpartner-371ec',
    authDomain: 'sparringpartner-371ec.firebaseapp.com',
    storageBucket: 'sparringpartner-371ec.appspot.com',
    measurementId: 'G-4QVGH882R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPyMmSCZl2zW1Hg2XA85cwVUl-Ti9iZI',
    appId: '1:740971362749:android:1441677a7c85e384c43ad4',
    messagingSenderId: '740971362749',
    projectId: 'sparringpartner-371ec',
    storageBucket: 'sparringpartner-371ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj7QKhXAb7P8sXC5oDaLDyDOxhVPvd0Wg',
    appId: '1:740971362749:ios:5a4a75a016b3be24c43ad4',
    messagingSenderId: '740971362749',
    projectId: 'sparringpartner-371ec',
    storageBucket: 'sparringpartner-371ec.appspot.com',
    iosBundleId: 'com.example.sparingPartners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj7QKhXAb7P8sXC5oDaLDyDOxhVPvd0Wg',
    appId: '1:740971362749:ios:79c7791e06ca4a37c43ad4',
    messagingSenderId: '740971362749',
    projectId: 'sparringpartner-371ec',
    storageBucket: 'sparringpartner-371ec.appspot.com',
    iosBundleId: 'com.example.sparingPartners.RunnerTests',
  );
}
